
development:
  adapter: postgresql
  encoding: unicode
  database: leonard_maltin_game_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: leonard_maltin_game_test
  pool: 5
  username: 
  password:

